leap_one_user_login:
  path: '/login'
  controller: VentureLeap\LeapOneSymfonySdk\Controller\UserController::login

leap_one_user_logout:
  path: '/logout'
  controller: VentureLeap\LeapOneSymfonySdk\Controller\UserController::logout

leap_one_user_reset_password:
  path: '/reset-password'
  controller: VentureLeap\LeapOneSymfonySdk\Controller\UserController::resetPasswordAction

## admin is the default user type
admin_mfa_check:
  path: '/mfa-check'
  controller: VentureLeap\LeapOneSymfonySdk\Controller\UserController::mfaCheck

leap_one_user_profile_show:
  path: '/profile'
  controller: VentureLeap\LeapOneSymfonySdk\Controller\UserController::profile
