# config/services.yaml
services:

  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  VentureLeap\LeapOneSymfonySdk\:
    resource: '../../../src/*'

  # MESSENGER
  VentureLeap\MessengerService\Api\MessageApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\MessengerApiProvider', 'getMessageApi' ]

  VentureLeap\MessengerService\Api\TemplateApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\MessengerApiProvider', 'getTemplateApi' ]

  VentureLeap\MessengerService\Api\ConfigurationEntryApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\MessengerApiProvider', 'getConfigurationEntryApi' ]

  # ORDER
  VentureLeap\OrderService\Api\OrderApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\OrderApiProvider', 'getOrderApi' ]

  VentureLeap\OrderService\Api\OrderProductApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\OrderApiProvider', 'getOrderProductApi' ]

  VentureLeap\OrderService\Api\VoucherApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\OrderApiProvider', 'getVoucherApi' ]

  VentureLeap\OrderService\Api\OrderVoucherApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\OrderApiProvider', 'getOrderVoucherApi' ]

  VentureLeap\OrderService\Api\ConfigurationEntryApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\OrderApiProvider', 'getConfigurationEntryApi' ]

  # RENDERER
  VentureLeap\RendererService\Api\RenderApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\RendererApiProvider', 'getRenderApi' ]

  VentureLeap\RendererService\Api\TemplateApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\RendererApiProvider', 'getTemplateApi' ]

  VentureLeap\RendererService\Api\ConfigurationEntryApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\RendererApiProvider', 'getConfigurationEntryApi' ]

  # USER
  VentureLeap\UserService\Api\UserApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\UserApiProvider', 'getUserApi' ]

  VentureLeap\UserService\Api\ConfigurationEntryApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\UserApiProvider', 'getConfigurationEntryApi' ]

  VentureLeap\UserService\Api\SocialAuthenticationApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\UserApiProvider', 'getSocialAuthenticationApi' ]

  VentureLeap\UserService\Api\AccountApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\UserApiProvider', 'getAccountApi' ]

  # AUDIT LOG
  VentureLeap\AuditLogService\Api\AuditLogEntryApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\AuditLogApiProvider', 'getAuditLogEntryApi' ]

  VentureLeap\AuditLogService\Api\ConfigurationEntryApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\AuditLogApiProvider', 'getConfigurationEntryApi' ]


  # Product
  VentureLeap\ProductService\Api\ProductApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\ProductApiProvider', 'getProductApi' ]

  VentureLeap\ProductService\Api\ProductCategoryApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\ProductApiProvider', 'getProductCategoryApi' ]

  VentureLeap\ProductService\Api\PriceListProductApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\ProductApiProvider', 'getPriceListProductApi' ]

  VentureLeap\ProductService\Api\PriceListApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\ProductApiProvider', 'getPriceListApi' ]

  VentureLeap\ConfigurationService\Api\ConfigurationEntryApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\ConfigurationApiProvider', 'getConfigurationEntryApi' ]

  # TOKEN
  VentureLeap\ConfigurationService\Api\TokenApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\TokenApiProvider', 'getTokenApi' ]

  # Rating
  VentureLeap\RatingService\Api\RatingApi:
    factory: [ '@VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\RatingApiProvider', 'getRatingApi' ]

  leap_one.user_provider:
    class: VentureLeap\LeapOneSymfonySdk\Services\User\UserProvider
    public: true

  # General credentials (to make it possible to override this logic in an application)
  # NEVER TOUCH THIS!
  VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\LeapOneConnectionCredentialsProviderInterface:
    class: VentureLeap\LeapOneSymfonySdk\Services\ApiProvider\LeapOneConnectionCredentialsProvider
    public: true
    arguments:
      $endpoint: '%env(string:LEAP_ONE_ENDPOINT_URL)%'
      $applicationId: '%env(string:LEAP_ONE_APP_ID)%'
      $applicationSecret: '%env(string:LEAP_ONE_APP_SECRET)%'

  # FORM AUTHENTICATION
  leap_one.login_form_authenticator:
    class: VentureLeap\LeapOneSymfonySdk\Services\Security\LoginFormAuthenticator
    public: true
    arguments:
      $routeAfterLogin: 'leap_one_user_profile_show'
      $loginRoute: 'leap_one_user_login'
      $userProvider: '@leap_one.user_provider'
    tags: [ 'leap_one.login_form_authenticators' ]

  # MFA AUTHENTICATION
  leap_one.mfa_authenticator:
    class: VentureLeap\LeapOneSymfonySdk\Services\Security\MfaAuthenticator
    public: true
    arguments:
      $routeAfterLogin: 'leap_one_user_profile_show'
      $loginRoute: 'leap_one_user_mfa_check'
      $userProvider: '@leap_one.user_provider'
    tags: [ 'leap_one.login_form_authenticators' ]

  Symfony\Bundle\SecurityBundle\Security\FirewallMap: '@security.firewall.map'
